### ISSUE TITLE
Consider using the .sh install rather than PPA ?

### ISSUE THREAD

**Issue by jasonhemann** [shriram/gradescope-racket#11]
An [outstanding bug](https://github.com/racket/racket/issues/2691) seems to get in the way of `raco` installing additional packages from the PPA racket. The .sh installation works around this. Would you consider a PR implementing the suggested work-around?

**Comment by shriram** [comment]
Yes, I'd love it!

**Comment by jasonhemann** [comment]
Submitted: https://github.com/shriram/gradescope-racket/pull/12
