### ISSUE TITLE
Modular way to specify point values of assignments

### ISSUE THREAD

**Issue by jasonhemann** [shriram/gradescope-racket#32]
The grader is right now fixed at a value out of 100. It'd be good to have some more flexible way to specify the point values of assignments.

Evenly weighted questions summing to some particular specified point value would be an improvement.

This opens the door to a wide variety of different evaluation models beyond, however, and I don't have a proposal about how to think of that.

**Comment by shriram** [comment]
I think this is a bottomless pit that is not especially worth going down. It also makes setup configuration much harder. And also, it may give students an inflated sense of the importance of autograding…

**Comment by jasonhemann** [comment]
I was pondering your discussion in the "Functional Geekery" podcast about how programming makes possible grading systems and schemes that otherwise couldn't be done. I think you're right---following this limits out at "just let them write their own code".

**Comment by shriram** [comment]
Right. They can just clone the repo and have at it.
